ignore:
  - "BackEnd-2/src/main/java/backend/security/*.java"  #ignore the JWT that thier tests we are making manually
  - "BackEnd-2/src/main/java/backend/googleSignIn/*.java"  #we cannot test this automatic because we need to take authtoken every time and it for use just once but we test it manually
  - "BackEnd-2/src/main/java/backend/CallParser/FitBitCallParser.java"  #we dont need to test this because we are not using it
  - "BackEnd-2/src/main/java/backend/emaiSend/*.java"  #we cannot test this automatic because we need to call google api everytime but we test it manually
  - "BackEnd-2/src/main/java/backend/Calendar/*.java"#we cannot test this automatic because we need to call apis but we test mannually
  